#page title
page_title                                :    a-Shell                                       # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1473805438                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                                                # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : a-Shell                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A text-based user interface for a screen-based platform

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nicolas Holzschuch                                
your_link                                 : https://github.com/holzschu/a-shell                     
your_city                                 : Grenoble                                
email_address                             : another_shell@icloud.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : a_Shell_iOS
github_username                           : holzschu
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : A Terminal in your pocket (or on your desk)
    description                           : The power of command line instructions, on your favorite device. 
    fontawesome_icon_name                 : terminal
    
  - title                                 : Control your files
    description                           : Create directories, move files, compress them, uncompress them, edit them, run python, lua or Tex on your files, move them to other apps.
    fontawesome_icon_name                 : file

  - title                                 : Check your network
    description                           : Check connectivity with ping, check site identity with nslookup or whois, transfer files with curl or scp...
    fontawesome_icon_name                 : wifi

  - title                                 : Edit your files inside the App
    description                           : "a-Shell comes with <a href='https://www.vim.org'>Vim</a> included. You can edit your files and even run syntax checkers using e.g. <a href='https://github.com/prabirshrestha/vim-lsp'>vim-lsp</a> or <a href='https://github.com/dense-analysis/ale'>ALE</a>. Or, if you're more old-school, there is also Ed."
    fontawesome_icon_name                 : edit

  - title                                 : Plays well with others
    description                           : a-Shell uses iOS file sharing ability. You can open directories in other app sandbox, run TeX or Python there, send the result in a third app. You can also edit files directly in a-Shell.
    fontawesome_icon_name                 : share-alt
  
  - title                                 : Multiple shell windows
    description                           : a-Shell uses iOS 13 multi-window ability. Edit your files in one window, process them in another, transfer them in a third...
    fontawesome_icon_name                 : window-restore

  - title                                 : Program on your iPad (or your iPhone)
    description                           : a-Shell comes with several programming languages: Lua, Python and C. Edit your programs and run them inside the app.
    fontawesome_icon_name                 : bug

  - title                                 : Install more packages
    description                           : Use "pip install" to add more Python packages (if they are pure Python, since there are no way to send the result of the C compiler to the app). 
    fontawesome_icon_name                 : archive

  - title                                 : Run your C files (yes, really)
    description                           : clang compiles your C files to LLVM intermediate representation (IR, or bytecode). Execute the resulting file using lli (LLVM interpreter).
    fontawesome_icon_name                 : paper-plane

  - title                                 : Available on TestFlight 
    description                           : "a-Shell is available on <a href='https://testflight.apple.com/join/WUdKe3f4'>TestFlight</a>."
    fontawesome_icon_name                 : vial

  - title                                 : OpenSource
    description                           : "a-Shell is entirely <a href='https://github.com/holzschu/a-Shell'>OpenSource</a>, and released under the FreeBSD license."
    fontawesome_icon_name                 : lock-open

  - title                                 : Suggestion box
    description                           : "Need more commands? Found a bug? Want to suggest a feature? Open an <a href='https://github.com/holzschu/a-shell/issues'>issue</a>."
    fontawesome_icon_name                 : envelope-open-text
    



  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
