#page title
page_title                                :    a-Shell                                       # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1473805438                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                                                # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : a-Shell                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A text-based user interface for a screen-based platform

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nicolas Holzschuch                                
your_link                                 : https://github.com/holzschu/a-shell                     
your_city                                 : Grenoble                                
email_address                             : another_shell@icloud.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : a_Shell_iOS
github_username                           : holzschu
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : A Terminal in your pocket (or on your desk)
    description                           : The power of command line instructions, on your favorite device. 
    fontawesome_icon_name                 : terminal
    
  - title                                 : iPhone Device Preview
    description                           : Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name                 : mobile

  - title                                 : Video Support
    description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome_icon_name                 : play-circle

  - title                                 : Automatic Icon and Metadata
    description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
    fontawesome_icon_name                 : sync

  - title                                 : Easy to Tweak
    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Feature List
    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : star

  - title                                 : Available on TestFlight 
    description                           : "a-Shell is available on <a href='https://testflight.apple.com/join/WUdKe3f4'>TestFlight</a>."
    fontawesome_icon_name                 : vial

  - title                                 : OpenSource
    description                           : "a-Shell is entirely <a href='https://github.com/holzschu/a-Shell'>OpenSource</a>, and released under the FreeBSD license."
    fontawesome_icon_name                 : lock-open

  - title                                 : Suggestion box
    description                           : "Need more packages? Found a bug? Want to suggest a feature? Open an <a href='https://github.com/holzschu/a-shell/issues'>issue</a>."
    fontawesome_icon_name                 : envelope-open-text
    



  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
